import { ArrowUpRight, CheckCircle2, CircleAlert, Layers3, PlayCircle, XCircle } from "lucide-react";

import { PipelineTable } from "@/components/dashboard/pipeline-table";
import { formatPercent, MetricCard } from "@/components/dashboard/shared";
import { PipelineTrend } from "@/components/charts/pipeline-trend";
import { StatusDonut } from "@/components/charts/status-donut";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import type { DashboardData, MetricBreakdown, PipelineSummary } from "@/lib/dashboard";

export function OverviewView({ data, onViewPipelines, onSelectPipeline }: { data: DashboardData; onViewPipelines: () => void; onSelectPipeline: (pipeline: PipelineSummary) => void }) {
  return <><div className="metric-grid"><MetricCard label="Visible projects" value={data.projects.length} detail="Available to this token" icon={Layers3} tone="blue" /><MetricCard label="Pipelines" value={data.metrics.totalPipelines} detail={`${data.metrics.successfulPipelines} successful · ${data.metrics.failedPipelines} failed`} icon={CheckCircle2} tone="teal" /><MetricCard label="Success rate" value={formatPercent(data.metrics.successRate)} detail="Completed pipelines" icon={CheckCircle2} tone="teal" /><MetricCard label="Running" value={data.metrics.runningPipelines} detail="Pending or executing now" icon={PlayCircle} tone="amber" /></div><div className="chart-grid"><Card><CardHeader><CardTitle>Pipeline throughput</CardTitle><CardDescription>Runs and outcomes over the last 24 hours</CardDescription></CardHeader><CardContent><PipelineTrend pipelines={data.pipelines} /></CardContent></Card><Card><CardHeader><CardTitle>Outcome mix</CardTitle><CardDescription>Pipeline status distribution</CardDescription></CardHeader><CardContent><StatusDonut pipelines={data.pipelines} /></CardContent></Card></div><div className="lower-grid"><BreakdownCard title="Failure reasons" description="Why failed jobs stopped delivery" icon={<CircleAlert size={16} />} items={data.metrics.failureReasons} empty="No failed jobs in the last 24 hours." /><BreakdownCard title="Failed stages" description="Stages containing failed jobs" icon={<XCircle size={16} />} items={data.metrics.failedStages} empty="No failed stages in the last 24 hours." /></div><Card><CardHeader className="table-card-header"><div><CardTitle>Latest pipelines</CardTitle><CardDescription>Click a row for job-level failure diagnostics</CardDescription></div><button className="text-link text-link-button" type="button" onClick={onViewPipelines}>View all <ArrowUpRight size={15} /></button></CardHeader><CardContent className="flush-content"><PipelineTable pipelines={data.pipelines} onSelect={onSelectPipeline} /></CardContent></Card></>;
}

function BreakdownCard({ title, description, icon, items, empty }: { title: string; description: string; icon: React.ReactNode; items: MetricBreakdown[]; empty: string }) {
  return <Card><CardHeader><CardTitle>{title}</CardTitle><CardDescription>{description}</CardDescription></CardHeader><CardContent>{items.length ? <div className="breakdown-list">{items.map((item) => <div className="breakdown-item" key={item.name}><span><span className="breakdown-name">{item.name.replaceAll("_", " ")}</span><span className="breakdown-bar"><span style={{ width: `${Math.min(100, item.count * 100 / Math.max(...items.map((entry) => entry.count))) || 0}%` }} /></span></span><strong>{item.count}</strong></div>)}</div> : <p className="breakdown-empty">{empty}</p>}</CardContent></Card>;
}
